// <auto-generated />
using System;
using EFCoreLearningProject1.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreLearningProject1.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251216103447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("EFCoreLearningProject1.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "English novelist and essayist.",
                            BirthDate = new DateTime(1903, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United Kingdom",
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "American science fiction writer and professor of biochemistry.",
                            BirthDate = new DateTime(1920, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United States",
                            FirstName = "Isaac",
                            LastName = "Asimov"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "English writer known for her detective novels.",
                            BirthDate = new DateTime(1890, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United Kingdom",
                            FirstName = "Agatha",
                            LastName = "Christie"
                        });
                });

            modelBuilder.Entity("EFCoreLearningProject1.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2025, 12, 16, 10, 34, 39, 830, DateTimeKind.Utc).AddTicks(6461),
                            AuthorId = 1,
                            GenreId = 1,
                            ISBN = "978-0451524935",
                            IsAvailable = true,
                            Price = 9.99m,
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2025, 12, 16, 10, 34, 39, 833, DateTimeKind.Utc).AddTicks(765),
                            AuthorId = 1,
                            GenreId = 1,
                            ISBN = "978-0451526342",
                            IsAvailable = true,
                            Price = 7.99m,
                            PublicationYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2025, 12, 16, 10, 34, 39, 833, DateTimeKind.Utc).AddTicks(783),
                            AuthorId = 2,
                            GenreId = 2,
                            ISBN = "978-0553293357",
                            IsAvailable = true,
                            Price = 8.99m,
                            PublicationYear = 1951,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2025, 12, 16, 10, 34, 39, 833, DateTimeKind.Utc).AddTicks(786),
                            AuthorId = 2,
                            GenreId = 2,
                            ISBN = "978-0553382563",
                            IsAvailable = true,
                            Price = 6.99m,
                            PublicationYear = 1950,
                            Title = "I, Robot"
                        });
                });

            modelBuilder.Entity("EFCoreLearningProject1.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fictional Literature",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sci-Fi books",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mystery and Thriller",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Biographical works",
                            Name = "Biography"
                        });
                });

            modelBuilder.Entity("EFCoreLearningProject1.Data.Models.Book", b =>
                {
                    b.HasOne("EFCoreLearningProject1.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreLearningProject1.Data.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("EFCoreLearningProject1.Data.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EFCoreLearningProject1.Data.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
